<?php
namespace DidUngar\ShippingBundle\Repository;

/**
 * TrackingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackingRepository extends \Doctrine\ORM\EntityRepository
{

}
